name: Hunter Creative
favicon: null
layout_spectrum: 0.93091
typography_spectrum: 0.9692193998489529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbece4'
    - '#001419'
    - '#00416c'
    - '#4d82a5'
    - '#9aaec0'
  brandStrength: 0.625
  lightness: 0.4569769052322954
  saturation: 0.38290188228711486
  rhythmicContrast: 0.6543531322386116
purpose: []
